name: Spencer
favicon: null
layout_spectrum: 0.6790276688989252
typography_spectrum: 0.7278671187814325
title: Web Site stuff for Chris Spencer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4935350315645337
  lightness: 0.5510753444395959
  saturation: 0.9489181074313819
  rhythmicContrast: 0.0633426473941654
purpose: []
